theme: jekyll-theme-cayman
title: 我的学习记录
email: lllpla.lee@outlook.com
url: https://lllpla.github.io
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "说点装逼的话。。。"
sidebar-avatar:/img/avatar-my.JPG
